version: 2

sources: 
  - name: staging 
    database: aerobic-badge-408610
    schema: all_ny_data

    tables: 
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata
      - name: zone_lookup